// ─────────────────────────────────────────────
//  QUARTETT — Fichier des défis
//  Format : { v: niveau (1-4), c: catégorie, t: texte, d: règle alcool }
//  Utilise {A} {B} {C} {D} pour les joueurs (tirés au sort à chaque défi)
// ─────────────────────────────────────────────

const CHALLENGES = [

  // ══════════════════════════════════════════
  //  NIVEAU 1 — Warm-up
  // ══════════════════════════════════════════

  { v:1, c:"Physique",  t:"{A} et {B} s'embrassent pendant 1 minute, langue obligatoire. Celui qui s'arrête en premier boit.",                                                                                d:"Premier à lâcher → shot." },
  { v:1, c:"Strip",     t:"{A} retire un vêtement de {B} avec les dents uniquement.",                                                                                                                         d:"S'il utilise les mains → il boit." },
  { v:1, c:"Physique",  t:"{A} et {B} se regardent dans les yeux sans sourire pendant 30 secondes. Celui qui sourit ou détourne le regard boit.",                                                            d:"Sourire ou regard détourné → shot." },
  { v:1, c:"Physique",  t:"{A} fait un massage des épaules à {B} pendant 1 minute. {B} ne peut pas faire de bruit.",                                                                                         d:"Si {B} gémit → il boit." },
  { v:1, c:"Physique",  t:"{A} s'allonge sur le dos, {B} s'allonge sur lui face contre face pendant 1 minute. Aucun déhanchement autorisé. Celui qui bouge les hanches boit.",                               d:"Mouvement de hanches → shot immédiat." },
  { v:1, c:"Strip",     t:"{A} fait un lap dance à {B} pendant 1 minute, sans s'arrêter. Vote du groupe /10 à la fin. Note < 6 → {A} boit.",                                                               d:"Note < 6 → verre entier." },
  { v:1, c:"Physique",  t:"{A} embrasse lentement {B} sur la joue, puis dans le cou, puis sur l'épaule — 10 secondes sur chaque zone. {B} ferme les yeux et ne peut pas bouger.",                            d:"Si {B} bouge ou ouvre les yeux → il boit." },
  { v:1, c:"Physique",  t:"{A} et {B} restent lèvres à lèvres sans s'embrasser pendant 20 secondes. Le premier qui craque et embrasse l'autre boit.",                                                        d:"Premier à craquer → shot." },
  { v:1, c:"Physique",  t:"{A} et {B} se font un câlin très serré pendant 45 secondes, visages dans le cou l'un de l'autre. Celui qui rigole boit.",                                                         d:"Celui qui rigole → shot." },
  { v:1, c:"Strip",     t:"{A} retire le pantalon de {B} aussi lentement que possible. {B} note /10. Note < 6 → {A} boit.",                                                                                  d:"Note < 6 → {A} boit." },
  { v:1, c:"Physique",  t:"{A} embrasse le cou de {B} pendant 30 secondes. {B} doit rester immobile. S'il bouge → il boit.",                                                                                 d:"Mouvement → shot." },
  { v:1, c:"Physique",  t:"{A} pose sa main à plat sur le ventre de {B} pendant 30 secondes. {B} garde les yeux fermés et ne peut pas faire de bruit.",                                                      d:"Si {B} gémit ou ouvre les yeux → il boit." },
  { v:1, c:"Physique",  t:"{A} s'assoit à cheval sur {B} pendant 1 minute. Aucun déhanchement. Celui qui cède en premier boit.",                                                                             d:"Mouvement de hanches → shot." },
  { v:1, c:"Physique",  t:"{A} et {C} s'embrassent à pleine bouche pendant 45 secondes. {B} et {D} regardent et votent /10. Note < 6 → les deux boivent.",                                                   d:"Note < 6 → les deux boivent." },
  { v:1, c:"Physique",  t:"{A} embrasse {B} sur la bouche pendant 1 minute, mains dans les cheveux de {B}. {B} garde les mains dans le dos.",                                                                d:"Si {B} sort les mains → il boit." },
  { v:1, c:"Strip",     t:"Tout le monde enlève une pièce de vêtement en même temps. Le dernier à finir boit.",                                                                                               d:"Dernier → shot." },
  { v:1, c:"Physique",  t:"{A} passe les deux mains dans les cheveux de {B} et le tient par la nuque pendant 30 secondes. {B} garde les yeux fermés. Si {B} ouvre les yeux → shot.",                    d:"Yeux ouverts → shot." },
  { v:1, c:"Physique",  t:"{B} et {C} guident chacun une main de {A} sur le corps de {D} pendant 30 secondes. {D} garde les yeux fermés.",                                                                   d:"Si {D} ouvre les yeux → il boit." },
  { v:1, c:"Strip",     t:"{A} retire la chemise de {B} avec les dents et les genoux uniquement. Il a 45 secondes. Utilise les mains ou dépasse le temps → il boit.",                                        d:"Mains ou temps dépassé → shot." },
  { v:1, c:"Physique",  t:"{A} tient {B} par la taille, joue contre joue, pendant 1 minute. Aucun des deux ne peut tourner la tête. Celui qui cède boit.",                                                   d:"Tête tournée → shot." },
  { v:1, c:"Physique",  t:"{C} frappe dans ses mains toutes les 10 secondes. {A} ne peut embrasser {B} que dans les 5 secondes qui suivent chaque frappe. Embrasse hors signal → shot. Durée : 1 minute.",   d:"Embrasse hors signal → shot." },
  { v:1, c:"Physique",  t:"{A} et {B} restent en contact physique (une partie du corps au minimum) pendant 1 minute. Ils peuvent bouger mais ne peuvent pas se séparer. Rupture de contact → shot.",          d:"Rupture → shot." },
  { v:1, c:"Physique",  t:"{A} s'assoit entre les jambes de {B}, dos contre torse, pendant 1 minute. Aucun des deux ne peut parler. Celui qui parle ou se décale boit.",                                     d:"Parole ou décalage → shot." },
  { v:1, c:"Physique",  t:"{A} s'agenouille entre les jambes écartées de {B} assis, sans le toucher, pendant 45 secondes. {B} ne peut pas fermer les jambes. Qui bouge le premier boit.",                    d:"Mouvement → shot." },
  { v:1, c:"Physique",  t:"{A} embrasse {B} dans le cou pendant que {C} embrasse {D} dans le cou — les deux duos côte à côte pendant 30 secondes. Vote du groupe : quel duo était le plus sexy. Perdants → shot.", d:"Perdants → shot." },
  { v:1, c:"Oral",     t:"{A} lèche le torse de {B} de haut en bas pendant 20 secondes. {B} garde les mains dans le dos et ne peut pas faire de bruit.",                                                       d:"Bruit ou mains → shot." },

  // ══════════════════════════════════════════
  //  NIVEAU 2 — Hot
  // ══════════════════════════════════════════

  { v:2, c:"Oral",           t:"{A} suce {B} pendant 2 minutes, sans les mains.",                                                                                                                             d:"Utilise les mains → boit et recommence." },
  { v:2, c:"Gorge profonde", t:"Duel : {A} vs {B}, gorge profonde sur {C} et {D}. {C} et {D} jugent. Le moins convaincant boit.",                                                                            d:"Perdant → deux shots." },
  { v:2, c:"Oral",           t:"{A} se fait lécher par {B} où {B} veut pendant 1 minute. {A} ne peut pas guider.",                                                                                           d:"Si {A} guide → il boit." },
  { v:2, c:"Strip",          t:"{A} fait un strip-tease complet. Vote du groupe /10. Note < 6 → il boit.",                                                                                                    d:"Note < 6 → verre entier." },
  { v:2, c:"Oral",           t:"{A} et {B} se sucent en même temps pendant 2 minutes. Celui qui s'arrête en premier boit.",                                                                                   d:"Premier à lâcher → shot." },
  { v:2, c:"Main",           t:"{A} branlé {B} à la main pendant 2 minutes sans s'arrêter ni changer de rythme. {B} doit rester immobile, mains dans le dos. {B} gémit ou bouge → shot. {A} s'arrête → shot.", d:"Faute → shot." },
  { v:2, c:"Physique",       t:"{A} se frotte contre {B} pendant 1 minute, les deux debout, {A} dans le dos de {B}. {B} ne peut pas bouger. Celui qui gémit boit.",                                         d:"Gémissement → shot." },
  { v:2, c:"Physique",       t:"{A} pose sa tête sur la cuisse de {B} pendant 1 minute. {B} ne peut pas poser de main sur {A}. {B} pose une main → shot. {A} s'assoit ou se relève → shot.",                d:"Faute → shot." },
  { v:2, c:"Oral",           t:"{A} tient la tête de {B} pendant que {B} suce {C} pendant 1 minute. {A} donne le rythme.",                                                                                   d:"Si {A} lâche → il boit." },
  { v:2, c:"Gorge profonde", t:"{A} essaie une gorge profonde sur {B}. Il a 2 minutes.",                                                                                                                     d:"Fail → boit. Succès → {B} boit." },
  { v:2, c:"Strip",          t:"Tout le monde se déshabille complètement. Le dernier nu boit.",                                                                                                               d:"Dernier → shot." },
  { v:2, c:"Main",           t:"{A} guide la main de {B} sur lui-même en n'utilisant que 4 mots : \"plus vite\", \"plus lent\", \"plus fort\", \"stop\". Durée 2 minutes. Tout autre mot → shot.",            d:"Mot hors liste → shot." },
  { v:2, c:"Oral",           t:"{C} et {D} sucent respectivement {A} et {B} pendant 2 minutes. Les récepteurs ne peuvent pas bouger.",                                                                       d:"Si un récepteur bouge → il boit." },
  { v:2, c:"Yeux bandés",    t:"{A} a les yeux bandés. On lui présente successivement la bite de {B}, {C} et {D} à identifier à la bouche. Une chance par joueur. Chaque erreur → shot pour {A}.",          d:"Chaque erreur → shot." },
  { v:2, c:"Oral",           t:"{A} lèche le torse de {B} de haut en bas pendant 1 minute sans lever la tête. {B} ne peut pas faire de bruit. S'il gémit → shot.",                                         d:"Gémissement → shot." },
  { v:2, c:"Main",           t:"{A} et {B} se branlent mutuellement pendant 2 minutes, interdit de se regarder l'un l'autre. Vote du groupe : qui avait la meilleure technique. Perdant → deux shots.",     d:"Perdant au vote → deux shots." },
  { v:2, c:"Oral",           t:"{A} tient les poignets de {B} dans son dos pendant que {B} suce {C} pendant 1 minute 30. Si {B} libère ses mains → {A} boit.",                                              d:"Mains libérées → {A} boit." },
  { v:2, c:"Oral",           t:"{A} se fait sucer par {B} et {C} en alternance, 30 sec chacun, 3 tours. Il annonce lequel était le meilleur. Le moins bien noté boit deux shots.",                          d:"Le moins bien noté → deux shots." },
  { v:2, c:"Prise",          t:"{A} prend {B} par derrière, pénétration maintenue, sans bouger les hanches pendant 1 minute. Celui qui commence à bouger en premier boit.",                                  d:"Mouvement de hanches → shot." },
  { v:2, c:"Oral",           t:"{A} suce {B} pendant que {C} suce {A} en même temps. Personne ne peut utiliser les mains. Durée : 1 minute 30. Qui s'arrête → shot.",                                      d:"Qui s'arrête → shot." },
  { v:2, c:"Gorge profonde", t:"Duel de tenue : {A} enfonce {B} dans sa gorge et tient immobile 25 secondes. Puis {C} fait de même avec {D}. Vote : quelle paire était la plus hot. Perdants → deux shots.", d:"Perdants → deux shots." },
  { v:2, c:"Oral",           t:"{A} suce {B} pendant 1 minute 30. Règle stricte : pas de pause de plus de 2 secondes. Le groupe compte les pauses. Plus de 3 pauses → {A} boit.",                           d:"Plus de 3 pauses → {A} boit." },
  { v:2, c:"Yeux bandés",    t:"{A} a les yeux bandés. {B}, {C} et {D} lui embrassent le cou, 30 sec chacun, dans un ordre tiré au sort. {A} annonce l'ordre à la fin. Chaque erreur → shot.",              d:"Chaque erreur → shot." },
  { v:2, c:"Prise",          t:"{A} prend {B} en doggy, pénétration maintenue, sans bouger les hanches pendant 1 minute 30. Le groupe chrono. Mouvement → shot.",                                           d:"Mouvement → shot." },
  { v:2, c:"Oral",           t:"{A} suce {B} pendant 1 minute pendant que {C} pose les deux mains sur la tête de {A} sans le guider. Si {C} appuie → shot pour {C}. Si {C} retire les mains → shot. {A} s'arrête → shot.", d:"Faute → shot." },
  { v:2, c:"Oral",           t:"{A} lèche les boules de {B} pendant 1 minute sans utiliser les mains. {B} doit rester immobile et silencieux. Gémit → shot. Bouge → shot.",                                   d:"Gémit ou bouge → shot." },
  { v:2, c:"Oral",           t:"{A} lèche le sexe de {B} de la base jusqu'au gland et retour, en continu pendant 1 minute. Pas de fellation — uniquement la langue de bas en haut. {B} ne peut pas guider.",  d:"Guide → shot." },
  { v:2, c:"Anal",           t:"{A} introduit un doigt dans {B} pendant 30 secondes. {B} doit rester immobile et silencieux. Bouge → shot. Gémit → shot.",                                                     d:"Faute → shot." },
  { v:2, c:"Oral",           t:"{A} et {B} s'allongent en 69 et se sucent mutuellement pendant 1 minute 30, sans les mains. Qui s'arrête ou utilise les mains → shot.",                                           d:"Faute → shot." },

  // ══════════════════════════════════════════
  //  NIVEAU 3 — Très chaud
  // ══════════════════════════════════════════

  { v:3, c:"Yeux bandés",     t:"{A} a les yeux bandés. {B}, {C} et {D} passent chacun 45 sec à lui sucer dans un ordre secret. Il doit retrouver l'ordre.",                                                d:"Chaque erreur → shot. 0 erreur → les 3 autres boivent." },
  { v:3, c:"Yeux bandés",     t:"{A} a les yeux bandés. Il se fait prendre par {B}, {C} et {D} dans un ordre tiré au sort (secret). Il annonce l'ordre ensuite.",                                           d:"Verre entier s'il se plante. Chaque bonne réponse économise un shot." },
  { v:3, c:"Endurance",       t:"{A} reçoit de {B}, {C} et {D} en rotation (1 min chacun). Il ne peut pas faire de bruit — pas un son. Chaque son audible → shot immédiat pour {A}.",                      d:"Chaque son → shot immédiat." },
  { v:3, c:"Couples croisés", t:"Les couples s'échangent : {A} avec {C}, {B} avec {D} pendant 3 minutes. Vote : quelle paire avait l'air la plus chaude ?",                                                 d:"La paire la moins convaincante → ils boivent." },
  { v:3, c:"Prise",           t:"{A} prend {B} pendant 3 minutes. Position imposée : debout, face à face, mains de {B} sur les épaules de {A} sans le tenir. Si les mains de {B} glissent ou se referment → shot.", d:"Mains qui glissent → shot." },
  { v:3, c:"Trio",            t:"Configuration trio fixe pendant 3 minutes : {A} prend {C} par derrière, {C} embrasse {B}, {B} suce {A}. Cette configuration ne change pas. Qui rompt → shot.",             d:"Rupture → shot." },
  { v:3, c:"Oral",            t:"Train oral : {A} suce {B}, {B} suce {C}, {C} suce {D} simultanément pendant 1 minute.",                                                                                    d:"Tout le monde boit si quelqu'un rigole." },
  { v:3, c:"Prise",           t:"{A} se fait prendre par {B} et {C} successivement (1 min 30 chacun). L'ordre est tiré au sort. {A} ne sait pas qui commence.",                                             d:"Chaque hésitation > 10 sec → shot pour l'hésitant." },
  { v:3, c:"Main",            t:"{A} branlé {B} à la main pendant 3 minutes sans s'arrêter. {B} doit garder les yeux grands ouverts et ne pas faire de bruit. Ferme les yeux → shot. Gémit → shot. {A} s'arrête → shot.", d:"Faute → shot." },
  { v:3, c:"Yeux bandés",     t:"{A} a les yeux bandés. {B} l'embrasse en changeant de zone toutes les 30 sec dans l'ordre imposé : bouche → cou → épaule → oreille. {A} annonce à chaque changement la nouvelle zone. Erreur → shot.", d:"Erreur → shot." },
  { v:3, c:"Gorge profonde",  t:"Tournoi gorge profonde : tout le monde essaie sur le joueur de son choix. Vote du groupe. Le moins bon boit deux verres.",                                                  d:"Dernier au classement → deux verres." },
  { v:3, c:"Prise",           t:"{B} et {C} prennent {A} en même temps (l'un devant, l'autre derrière). Ils tiennent 2 minutes sans s'arrêter.",                                                            d:"Qui s'arrête avant → verre entier." },
  { v:3, c:"Yeux bandés",     t:"{A} a les yeux bandés et les mains dans le dos. {B}, {C} et {D} lui font chacun une action différente en simultané pendant 1 minute. {A} doit dire exactement ce que fait chacun. Chaque erreur → shot.", d:"Chaque erreur → shot." },
  { v:3, c:"Endurance",       t:"{A} embrasse le cou de {B} pendant 2 minutes sans interruption. {B} doit rester silencieux et immobile. {B} gémit → shot. {B} bouge → shot. {A} s'arrête → il boit.",     d:"Faute → shot." },
  { v:3, c:"Oral",            t:"{A} se fait sucer par {B} pendant 2 minutes. {A} peut utiliser uniquement ces 4 mots : \"plus vite\", \"plus lent\", \"plus fort\", \"stop\". Il doit en dire au moins 8 au total. Mot hors liste → shot. Moins de 8 → shot.", d:"Faute → shot." },
  { v:3, c:"Prise",           t:"Duel de prises : {A} prend {B} pendant 2 minutes, puis {C} prend {D} pendant 2 minutes. Vote groupe : quelle paire était la plus hot ? Les perdants boivent deux verres.",  d:"Perdants → deux verres." },
  { v:3, c:"Gorge profonde",  t:"{A} essaie une gorge profonde sur {B} avec chrono. Réussite en moins de 30 sec → {B} boit. Entre 30 sec et 1 min → {A} boit. Après 1 min → {A} boit deux verres.",        d:"Fail total → deux verres." },
  { v:3, c:"Trio",            t:"Trio en rythme synchronisé : {A} prend {C} par derrière, {C} suce {B}. Le groupe annonce \"lent\" puis \"rapide\" toutes les 20 secondes. {A} et {C} changent de rythme ensemble. Désynchronisation → shot.", d:"Désynchronisation → shot." },
  { v:3, c:"Oral",            t:"{A} suce {B} pendant 3 minutes sans s'arrêter ni utiliser les mains. {B} ne peut pas faire de bruit. {B} gémit → shot. {A} s'arrête ou utilise les mains → shot.",         d:"Faute → shot." },
  { v:3, c:"Couples croisés", t:"{A} avec {B}, {C} avec {D} pendant 1 minute. Puis échange de partenaire automatique toutes les 30 sec pendant 2 minutes. 4 échanges au total. Pause > 5 sec entre échanges → shot.", d:"Pause > 5 sec → shot." },
  { v:3, c:"Endurance",       t:"{A} est pris par {B} en doggy. {C} et {D} essaient de faire rire ou parler {A} en 2 minutes (sans le toucher). {A} ne peut pas faire de bruit. Le moindre son → shot pour {A}.", d:"Son → shot pour {A}." },
  { v:3, c:"Gorge profonde",  t:"{A} enchaîne les gorges profondes : {B} pendant 30 sec, puis {C} pendant 30 sec, puis {D} pendant 30 sec, sans pause entre les passages. Vote final : quelle passe était la plus hot.", d:"Arrêt → shot." },
  { v:3, c:"Prise",           t:"{A} prend {B} en 3 positions successives imposées : face à face debout / doggy / cuiller — 1 minute chacune. Transition < 5 sec. Pause > 5 sec → shot pour les deux.",      d:"Pause > 5 sec → shot." },
  { v:3, c:"Couples croisés", t:"{A}+{B} et {C}+{D} chacun en prise pendant 2 minutes. Exactement à 2 minutes, les deux duos échangent les rôles sans s'arrêter. Pause > 5 sec entre les deux phases → shot.", d:"Pause > 5 sec → shot." },
  { v:3, c:"Oral",            t:"{A} suce {B} et {C} en alternance, 45 sec chacun, 2 tours. {D} annonce chaque passage. {A} s'arrête pendant un passage → shot. {D} oublie d'annoncer → {D} boit.",          d:"Faute → shot." },
  { v:3, c:"Anal",           t:"{A} compte les verres sur la table : ≤ 3 verres → 1 doigt 20 sec · 4 à 6 verres → 1 doigt 40 sec · 7 verres et plus → 2 doigts 30 sec. {B} reste immobile et silencieux. Bouge ou gémit → shot.", d:"Faute → shot." },
  { v:3, c:"Anal",           t:"{A} introduit un doigt dans {B} pendant que {B} suce {C}. {B} ne peut pas s'arrêter de sucer. Durée 1 minute. S'arrête → shot. Gémit → shot.",                                d:"Faute → shot." },
  { v:3, c:"Prise",          t:"{A} s'assoit à cheval sur {B} dos tourné (reverse cowboy), pénétration maintenue, mains de {A} dans le dos pendant 1 minute 30. {A} s'appuie avec les mains → shot. {A} descend → shot.", d:"Faute → shot." },
  { v:3, c:"Trio",           t:"Cuiller à 3 : {A} prend {B} en cuiller, {C} prend {A} en cuiller derrière lui — tous allongés sur le côté. Les deux pénétrations tenues simultanément 2 minutes. Qui rompt → les deux concernés boivent.", d:"Rupture → les deux concernés boivent." },
  { v:3, c:"Double péné",    t:"{A} reçoit {B} et {C} en double pénétration pendant que {A} suce {D}. Tenir 1 minute 30 sans pause. Si l'une des 3 positions cède → les 3 concernés par la DP boivent.",      d:"Cède → les 3 boivent." },

  // ══════════════════════════════════════════
  //  NIVEAU 4 — Extrême
  // ══════════════════════════════════════════

  { v:4, c:"Extrême", t:"{A} est au centre. {B} le prend par derrière, {C} lui suce devant, {D} lui suce le cou et l'embrasse. Le groupe tient 3 minutes sans s'arrêter. Qui lâche → deux verres.",          d:"Rupture → deux verres." },
  { v:4, c:"Extrême", t:"{A} a les yeux bandés et les mains dans le dos. {B}, {C} et {D} se relaient sur lui (1 min 30 chacun) dans un ordre tiré au sort. À la fin, {A} identifie qui est passé dans quel ordre.", d:"Tous correctement identifiés → les 3 autres boivent double. Chaque erreur → shot." },
  { v:4, c:"Extrême", t:"Gang bang : {A} reçoit chacun en rotation (1 min par joueur). L'ordre est tiré au sort, {A} tient le chrono.",                                                                       d:"Qui coupe court → deux verres." },
  { v:4, c:"Extrême", t:"Tous les 4 ensemble pendant 4 minutes. Rôles tirés au sort : pénètre / reçoit / suce / chrono et signale les changements toutes les 45 sec. Changer de rôle sans signal → verre entier.", d:"Changement non autorisé → verre entier." },
  { v:4, c:"Extrême", t:"Ronde imposée : {B} prend {A} pendant 1 minute 30, puis {C} pendant 1 minute 30, puis {D} pendant 1 minute 30. {A} ne peut pas bouger les hanches ni faire de bruit. Mouvement → shot. Son → shot.", d:"Mouvement ou son → shot." },
  { v:4, c:"Extrême", t:"Deux duos simultanés ({A}+{C}) et ({B}+{D}) dans la même pièce pendant 3 minutes. Interdit de s'arrêter pour regarder.",                                                             d:"Qui s'arrête pour regarder → shot immédiat." },
  { v:4, c:"Extrême", t:"{A} se fait prendre par {B} pendant que {C} suce {A}. {D} peut donner uniquement deux ordres : \"accélère\" ou \"ralentit\", toutes les 30 sec. Toute autre intervention de {D} → {D} boit.", d:"Intervention hors cadre → {D} boit." },
  { v:4, c:"Extrême", t:"Vote confiance : qui fait le plus confiance aux autres ? Le gagnant est allongé, yeux bandés, pendant 3 minutes. {B}, {C} et {D} l'embrassent et lui sucent le cou en silence. Le gagnant ne peut pas bouger. Bouge → il boit.", d:"Le gagnant refuse → tout le monde boit sauf lui." },
  { v:4, c:"Extrême", t:"Configuration imposée pendant 4 minutes : {B} prend {A} par derrière, {C} suce {A} devant, {D} embrasse {B}. Cette position ne change pas. Qui s'arrête → deux verres.",             d:"Arrêt → deux verres." },
  { v:4, c:"Extrême", t:"Tous les 4, yeux bandés pendant 2 minutes. Règle prédéfinie : les mains restent sur le torse et le dos uniquement — pas sous la ceinture. Qui enfreint → verre entier.",             d:"Infraction → verre entier." },
  { v:4, c:"Extrême", t:"{A} est allongé, immobile, mains dans le dos. {B}, {C} et {D} se relaient sur lui (1 min 30 chacun) dans un ordre tiré au sort. {A} ne peut pas faire de bruit. Chaque son audible → shot immédiat.", d:"Son audible → shot immédiat." },
  { v:4, c:"Extrême", t:"Duel de tenue simultané : {A} prend {B}, {C} prend {D}, en même temps pendant 3 minutes. Pénétration maintenue sans piston. Mouvement de hanches → shot immédiat pour le duo.",      d:"Mouvement → shot immédiat." },
  { v:4, c:"Extrême", t:"{A} reçoit {B} par derrière pendant que {C} lui enfonce dans la gorge. Rythme synchronisé : {D} donne le tempo à voix haute toutes les 30 secondes. Qui dérègle le rythme → shot.",  d:"Dérèglement → shot." },
  { v:4, c:"Extrême", t:"{A} a les yeux bandés, à genoux. {B}, {C} et {D} ont chacun un rôle assigné par tirage au sort : suce / prend par derrière / branlé — 1 min 30 chacun, ordre secret. {A} doit retrouver l'ordre et qui a fait quoi. Chaque erreur → shot.", d:"Chaque erreur → shot." },
  { v:4, c:"Extrême", t:"{A} et {B} enchaînent 4 positions dans l'ordre imposé : face à face debout / doggy / cuiller / missionnaire — 1 minute chacune. Pause > 5 sec entre deux positions → shot pour les deux.", d:"Pause > 5 sec → shot." },
  { v:4, c:"Extrême", t:"Train complet : {D} prend {C}, {C} suce {B}, {B} suce {A} — tous en simultané pendant 2 minutes. Puis rotation d'un cran : 2 minutes supplémentaires. Qui rompt la chaîne → deux verres.", d:"Rupture de chaîne → deux verres." },
  { v:4, c:"Extrême", t:"{A} est pris par {B} en missionnaire pendant que {C} s'assoit sur le visage de {A}. Cette configuration fixe tient 3 minutes. Qui bouge de sa position → deux verres. {D} chrono et annonce chaque minute.", d:"Rupture → deux verres." },
  { v:4, c:"Extrême", t:"Cercle de 4 : chacun a une main sur le voisin de gauche, en continu pendant 3 minutes. Qui retire sa main → shot. Qui ralentit nettement → shot. Le groupe chrono.",                  d:"Faute → shot." },
  { v:4, c:"Extrême", t:"{A} suce successivement {B}, {C} et {D} pendant 1 minute chacun, sans pause entre les passages. Chacun note /10. Total < 21 → {A} boit deux verres.",                                d:"Total < 21 → {A} boit deux verres." },
  { v:4, c:"Extrême", t:"Enchaînement imposé : phase 1 (1 min 30) : {B} prend {A}, {C} suce {A}, {D} embrasse {B}. Phase 2 (1 min 30) : {C} prend {D}, {A} suce {D}, {B} embrasse {C}. Pas de pause entre les phases. Pause → deux verres.", d:"Pause → deux verres." },
  { v:4, c:"Extrême", t:"Rotation gang bang positions imposées : {A} reçoit {B} en doggy (1 min 30), puis {C} en missionnaire (1 min 30), puis {D} debout face à face (1 min 30). Chaque transition < 5 sec. Délai > 5 sec → shot.", d:"Délai > 5 sec → shot." },
  { v:4, c:"Extrême", t:"{A} a les yeux bandés, allongé. {B}, {C} et {D} le sucent successivement (1 min chacun, ordre tiré au sort), puis le prennent successivement (1 min chacun, ordre différent tiré au sort). {A} annonce les deux ordres. Chaque erreur → shot.", d:"Chaque erreur → shot." },
  { v:4, c:"Extrême", t:"Immobilité à 4 : {A} est pris par {B}, pénétration maintenue. {C} embrasse {A}, {D} embrasse {B}. Les 4 restent parfaitement immobiles pendant 2 minutes. Tout mouvement → shot pour le duo concerné.", d:"Mouvement → shot." },
  { v:4, c:"Extrême", t:"{A} reçoit {B} pendant que {C} suce {A}. Rythme imposé : 10 coups lents (1 toutes les 2 sec), puis 10 rapides (1 par sec), en boucle. Le groupe compte à voix haute. Dérèglement → shot.", d:"Dérèglement → shot." },
  { v:4, c:"Extrême", t:"Vote en début de défi : le groupe désigne la paire la plus hot ({A}+{B} ou {C}+{D}). La paire gagnante se suce mutuellement et simultanément pendant 3 minutes sous les yeux des deux autres. Les deux autres restent immobiles. Intervention → shot.", d:"Intervention → shot." },
  { v:4, c:"Extrême", t:"{A} reçoit {B} pendant que {C} lui introduit deux doigts simultanément. Double pénétration maintenue pendant 2 minutes. {A} ne peut pas faire de bruit. Chaque son → shot.",          d:"Son → shot." },
  { v:4, c:"Double péné",    t:"{B} assis, {A} à cheval sur lui (pénétré, face à face). {C} prend {A} par derrière simultanément. Double pénétration tenue 2 minutes. {D} chrono. Si l'un des 3 cède → les 3 boivent.", d:"Cède → les 3 boivent." },
  { v:4, c:"Trio",           t:"Triangle oral : {A} allongé sur le dos, {B} assis sur son visage dos vers lui, {B} se penche et suce {C} agenouillé devant. Les 3 simultanément pendant 1 minute 30. Si l'un cède → les 3 boivent.", d:"Cède → les 3 boivent." },
  { v:4, c:"Double péné",    t:"Pyramide : {B} allongé, {A} à cheval sur lui face à face (pénétré). {C} prend {A} par derrière simultanément — DP pour {A}. {D} suce {B} en même temps. Configuration tenue 2 minutes. Si l'une des 3 positions cède → les 3 boivent.", d:"Cède → les 3 boivent." },

];
